export const tokens = [
  {
    id: "1",
    name: "Dinari USD",
    symbol: "dUSD",
    balance: 5000,
    value: 5000,
    iconSymbol: "usdc",
    isStablecoin: true,
  },
  {
    id: "2",
    name: "Dinari Tesla",
    symbol: "dTSLA",
    balance: 10,
    value: 2450,
    iconSymbol: "tsla",
  },
  {
    id: "3",
    name: "Bitcoin",
    symbol: "BTC",
    balance: 0.25,
    value: 15000,
    iconSymbol: "btc",
  },
  {
    id: "4",
    name: "Ethereum",
    symbol: "ETH",
    balance: 2.5,
    value: 7500,
    iconSymbol: "eth",
  },
  {
    id: "5",
    name: "Solana",
    symbol: "SOL",
    balance: 50,
    value: 5000,
    iconSymbol: "sol",
  },
  {
    id: "6",
    name: "Cardano",
    symbol: "ADA",
    balance: 2000,
    value: 1000,
    iconSymbol: "ada",
  },
  {
    id: "7",
    name: "Polkadot",
    symbol: "DOT",
    balance: 100,
    value: 800,
    iconSymbol: "dot",
  },
  {
    id: "8",
    name: "Chainlink",
    symbol: "LINK",
    balance: 75,
    value: 750,
    iconSymbol: "link",
  },
  {
    id: "9",
    name: "Uniswap",
    symbol: "UNI",
    balance: 50,
    value: 300,
    iconSymbol: "uni",
  },
  {
    id: "10",
    name: "Aave",
    symbol: "AAVE",
    balance: 5,
    value: 400,
    iconSymbol: "aave",
  },
  {
    id: "11",
    name: "Avalanche",
    symbol: "AVAX",
    balance: 20,
    value: 600,
    iconSymbol: "avax",
  },
  {
    id: "12",
    name: "Polygon",
    symbol: "MATIC",
    balance: 1000,
    value: 900,
    iconSymbol: "matic",
  },
  {
    id: "13",
    name: "Binance Coin",
    symbol: "BNB",
    balance: 5,
    value: 1500,
    iconSymbol: "bnb",
  },
  {
    id: "14",
    name: "Tether",
    symbol: "USDT",
    balance: 2000,
    value: 2000,
    iconSymbol: "usdt",
    isStablecoin: true,
  },
  {
    id: "15",
    name: "USD Coin",
    symbol: "USDC",
    balance: 1500,
    value: 1500,
    iconSymbol: "usdc",
    isStablecoin: true,
  },
  {
    id: "16",
    name: "Dai",
    symbol: "DAI",
    balance: 1000,
    value: 1000,
    iconSymbol: "dai",
    isStablecoin: true,
  },
  {
    id: "17",
    name: "Shiba Inu",
    symbol: "SHIB",
    balance: 10000000,
    value: 200,
    iconSymbol: "shib",
  },
  {
    id: "18",
    name: "Dogecoin",
    symbol: "DOGE",
    balance: 5000,
    value: 350,
    iconSymbol: "doge",
  },
  {
    id: "19",
    name: "Cosmos",
    symbol: "ATOM",
    balance: 30,
    value: 300,
    iconSymbol: "atom",
  },
  {
    id: "20",
    name: "Algorand",
    symbol: "ALGO",
    balance: 500,
    value: 150,
    iconSymbol: "algo",
  },
];

export const getTokenById = (id: string) => {
  return tokens.find((token) => token.id === id);
};

export const getTokenBySymbol = (symbol: string) => {
  return tokens.find(
    (token) => token.symbol.toLowerCase() === symbol.toLowerCase()
  );
};
